server:
  port: 9097

route-config-pricing:
  pricing:
    from: 'activemq:queue:Consumer.${spring.application.name}.VirtualTopic.pricing.marketdata?jmsMessageType=Text&testConnectionOnStartup=true'

pricing:
  expiry: 5000

spring:
  application:
    name: 'pricing'
  redis:
    client-name: ${spring.application.name}-${HOSTNAME}
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  activemq:
    broker-url: ${ACTIVEMQ_HOST}
    password: ${ACTIVEMQ_PASSWORD}
    user: ${ACTIVEMQ_USERNAME}
    pool:
      enabled: true

camel:
  component:
    activemq:
      broker-url: ${ACTIVEMQ_HOST}
      username: ${ACTIVEMQ_USERNAME}
      password: ${ACTIVEMQ_PASSWORD}
  dataformat:
    json-jackson:
      module-class-names: com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
      disable-features: WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS,WRITE_DATES_AS_TIMESTAMPS