server:
  port: 9099

schema_name: ${spring.application.name}

cg:
  comp-id: 'ELDORADO'
  jwt:
    secret: ${JWT_SECRET}
    expiry: 3600000
  market-data:
    base-url: ${MARKET_DATA_BASE_URL}
    path: ${MARKET_DATA_PATH}

route-config:
  new-order:
    from: 'activemq:queue:Consumer.${spring.application.name}.VirtualTopic.oms.execution-reports?jmsMessageType=Text&testConnectionOnStartup=true'
    to: 'activemq:topic:VirtualTopic.${spring.application.name}.new-order?jmsMessageType=Text&testConnectionOnStartup=true'

spring:
  application:
    name: client-gateway
  datasource:
    url: jdbc:mysql://${mysql_rds_host}:${mysql_rds_port}/${schema_name}?createDatabaseIfNotExist=true
    hikari:
      username: ${mysql_rds_username}
      password: ${mysql_rds_password}
      auto-commit: true
      pool-name: ${spring.application.name}-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        serverTimezone: UTC
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      show-sql: false
      properties:
        hibernate.jdbc.time_zone: UTC
        hibernate.cache.use_second_level_cache: true
        hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        javax.persistence.sharedCache: ENABLE_SELECTIVE
    liquibase:
      enabled: true
      rollback-file: /app/service/liquibase/rollback.sql
      test-rollback-on-update: true
  activemq:
    broker-url: ${ACTIVEMQ_HOST}
    password: ${ACTIVEMQ_PASSWORD}
    user: ${ACTIVEMQ_USERNAME}
    pool:
      enabled: true

camel:
  component:
    activemq:
      broker-url: ${ACTIVEMQ_HOST}
      username: ${ACTIVEMQ_USERNAME}
      password: ${ACTIVEMQ_PASSWORD}
  dataformat:
    json-jackson:
      module-class-names: com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
      disable-features: WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS,WRITE_DATES_AS_TIMESTAMPS
